disposable-email-domains/disposable-email-domains

- disposable_email_blacklist.conf
Had a few that weren't on the list. Most of them are from the the cock.li troll email service as well as 10minutemail.net's current domain
> Merged in my list

- README.md
Let a comment to avoid undefined offset.
That was also the case with the previous example.
> Simplified PHP code again

- disposable_email_blacklist.conf
Naver email domain seems to be frequently used in South Korea, and not as a disposable email provider.
> Remove Naver from disposable email list

- disposable_email_blacklist.conf
It is a real email service, not a disposable one.
Belongs to Tomtel Internet-provider in Tomsk, Russia.
http://www.tomtel.ru/adds.html
> Remove sibmail.com from disposable email list.

- disposable_email_blacklist.conf
This pull request adds more domains used by [trashmail.com](https://trashmail.com/?cmd=features).
> Blacklist domains from trashmail.com

- disposable_email_blacklist.conf
See this line: https://github.com/martenson/disposable-email-domains/blob/master/disposable_email_blacklist.conf#L1424
> Removed pcusers.otherinbox.com as otherinbox.com is already black listed

- disposable_email_blacklist.conf
See http://drs.ua/ and http://pp.ua/
See also the wikipedia article https://en.wikipedia.org/wiki/.ua
I also reintroduced `add3000.pp.ua`, `ass.pp.ua`, `get.pp.ua`, `ip4.pp.ua`, `ip6.pp.ua`, `loh.pp.ua`, `mox.pp.ua`, `stop-my-spam.pp.ua`, `yopmail.pp.ua` domains
There're already some subdomains entries for `pp.ua` in the `blacklist`file:
- `web-mail.pp.ua`
- `eml.pp.ua`
- `fake-email.pp.ua`
- `jetable.pp.ua`
See https://email-fake.com/mox.pp.ua/tarjeixsi for the list of all `pp.ua` fake domains.
> Removed pp.ua domain as it's an ukrainian regristar for private domain

- README.md
Also updates links to https://pypi.org instead, and adds syntax highlighting for the Python example.
> Link to contributors

- disposable_email_blacklist.conf
- whitelist.conf
The National University of Singapore should be in the whitelist.
http://nus.edu.sg
> NUS email removal

- disposable_email_blacklist.conf
lakqs.com is from https://10minutemail.net.
kpooa.com is from https://10minutemail.org.
pqoia.com is from https://10minutemail.info.
They change the disposable domain every 45 days. These are the new ones.
> Add latest 10minutemail.* domains

- disposable_email_blacklist.conf
- verify.py
Adds some more checks to the CI:
* checks that all domains are lowercase
* checks that domains don't appear more than once in a list
* checks that the lists are sorted alphanumerically
* checks that a domain doesn't appear in both the whitelist and blacklist
This also fixes some failures of those tests, namely that #172 added a domain that wasn't in the correct place alphabetically, and #174 added some domains that were in the whitelist already.
> Add more CI checks

- disposable_email_blocklist.conf
Seems to be one of the domains used by burnermail.io.
> Add tryninja.io

- disposable_email_blocklist.conf
fixes https://github.com/martenson/disposable-email-domains/issues/189
> add emaildrop.io to blocklist

- disposable_email_blocklist.conf
Our company owns these Sudo domains.
We have made improvements to our app to limit the disposability of our email addresses (only paying users are allowed to use the app, we are working to limit the amount of email resets, etc.). Additionally, we have elaborate fraud monitoring, ensuring that our users are not spamming others. A significant amount of our users are reporting that their emails are getting blocked. We are working to clear our name from multiple blacklist providers, and noticed that several email providers rely on this repo.
> Remove Sudo domains

- disposable_email_blocklist.conf
https://10minutemail.net service uses new `cndps.com` domain. 
[![screenshot](https://i.gyazo.com/9b9c02c3f6c77e44e521321914503780.png)](https://gyazo.com/9b9c02c3f6c77e44e521321914503780)
> Adding cndps.com to a list

- disposable_email_blocklist.conf
Domains provided by https://temp-mail.org service:
```
amail1.com
mail-help.net
email1.pro
mail1web.org
mailhub.pro
imail1.net
max-mail.org
quick-mail.cc
mail1.top
swift-mail.net
```
> Blacklist temp-mail.org domains

- disposable_email_blocklist.conf
Hiya, this is an awesome project!
I noticed that [33Mail](https://www.33mail.com/about) was on the `email_blocklist.conf`, but this service is not a temporary mail provider, and requires users to create an account, with valid contact details, and payment details (for premium plan). 
Since it's a privacy service, not a disposable email address, I'm making the suggestion that it probably doesn't need to be on this list? especially since there are no other forwarding mail providers included here
---
**Bit of Background**
Email alias forwarding services work by allowing users to use a different email alias for each online service (e.g. `facebook@john.33mail.com`, `github@my-domain.com`, `heroku@john.anonaddy.com`, etc). It enables users to protect their real email address, when creating …
> Suggests Removeing 33Mail

- disposable_email_blocklist.conf
Looks like https://github.com/martenson/disposable-email-domains/pull/246 was merged w/ failing CI.
> Fix sort order

- disposable_email_blocklist.conf
- bestlistbase.com
- chasefreedomactivate.com
- truthfinderlogin.com
- wellsfargocomcardholders.com
See: https://www.linshiyouxiang.net/
Signed-off-by: Hollow Man <hollowman@hollowman.ml>
> Add more linshiyouxiang.net related domains

- README.md
- maintain.sh
My system's localization settings are Chinese, I won't produce the same order as the repo list using `cat disposable_email_blocklist.conf your_file | tr '[:upper:]' '[:lower:]' | sort -f | uniq -i > new_file.conf` unless executing `LC_ALL=C; export LC_ALL` beforehand.
Signed-off-by: Hollow Man <hollowman@hollowman.ml>
> Add a shell script for maintaining disposable_email_blocklist.conf

- README.md
- disposable_email_blocklist.conf
Hello :wave:
I got a lot of disposable emails from this `firemailbox.club` domain on my project and noticed it's not yet in the list.
Here is where we can generate disposable email on this domain: https://www.mohmal.com/fr/inbox
And here is another third-party classifying this domain as disposable: https://www.ipqualityscore.com/domain-reputation/firemailbox.club
Edit: I also discovered and added:
- `inboxkitten.com` (link to generate emails: https://inboxkitten.com/, same third-party classifying as disposable: https://www.ipqualityscore.com/domain-reputation/inboxkitten.com)
- `tmpbox.net` (link to generate emails: https://www.moakt.com/, third-party: https://www.ipqualityscore.com/domain-reputation/tmpbox.net)
- `moakt.cc` (another domain from https://www.moakt.com/, I checked the …
> Add firemailbox.club, inboxkitten.com, tmpbox.net & more.. disposable domains

- disposable_email_blocklist.conf
This is a web service used to debug webhooks and emails. Generates disposable email addresses under the `email.webhook.site` domain.
Details: https://docs.webhook.site/index.html
> Added webhook.site

- disposable_email_blocklist.conf
Add the domains provided by InstAddr to blocklist
- ccmail[.]uk
- exdonuts[.]com
- na-cat[.]com
- uma3[.]be
- xmailer[.]be
InstAddr is a site that provides disposable email addresses.
The domains added by this PR can be found below.
https://m.kuku.lu/config_domain.php
We can generate new disposable email from the link "Designate an address" in https://m.kuku.lu/index.php
> Add the domains provided by InstAddr to blocklist

- disposable_email_blocklist.conf
`onetm[.]jp` can be obtained by following the steps.
1. Access to https://www.onetime-mail.com/ (Japanese only)
2. Click "免責事項に同意し今すぐ利用する" 
- <img src="https://user-images.githubusercontent.com/1357608/141406631-fcde516c-01eb-4e12-8e9b-26cc76f9c93c.png" width="480px" />
3. Disposable email is available
- <img src="https://user-images.githubusercontent.com/1357608/141407008-0d625a2d-d452-449b-b52b-c20e60fdffce.png" width="480px" />
> add onetm.jp

- disposable_email_blocklist.conf
Add the following domains to the block list
- getover[.]de
- tdtda[.]com
- uuf[.]me
Email addresses for these domains can be obtained from https://mail.td
> Add domains available on https://mail.td/

- disposable_email_blocklist.conf
Add dea-21olympic[.]com to blocklist
Email addresses for this domain can be obtained from http://15qm.com/
.|.
---|---
> Add dea-21olympic.com to blocklist

- allowlist.conf
- disposable_email_blocklist.conf
Fixes #300. This domain doesn't meet our standards for a disposable email domain.
> Move shitware.nl to allowlist

- disposable_email_blocklist.conf
https://temp-mail.org/ based on IP
- petloca.com - https://www.mailcheck.ai/domain/petloca.com - 164.90.252.249
- alfaceti.com - https://www.mailcheck.ai/domain/alfaceti.com - 164.90.252.249
- goonby.com - https://www.mailcheck.ai/domain/goonby.com - 164.90.252.249
- chatich.com - https://www.mailcheck.ai/domain/chatich.com - 164.90.252.249
- balaket.com - https://www.mailcheck.ai/domain/balaket.com - 164.90.252.249
- bepureme.com - https://www.mailcheck.ai/domain/bepureme.com - 164.90.252.249
- plexfirm.com - https://www.mailcheck.ai/domain/plexfirm.com - 164.90.252.249
- diolang.com - https://www.mailcheck.ai/domain/diolang.com - 164.90.252.249
- wekawa.com - - 164.90.252.249
- taukah.com - - 164.90.252.249
Other:
- suexamplesb.com - https://www.emailondeck.com/eod.php
- …
> feat: update for 2022-02-11

- disposable_email_blocklist.conf
foreastate.com - https://www.mailcheck.ai/domain/foreastate.com - https://www.fakemail.net/
vixtricks.com - https://www.mailcheck.ai/domain/vixtricks.com - https://temp-mail.org/ - 164.90.252.249
sheryli.com - https://www.mailcheck.ai/domain/sheryli.com - https://temp-mail.org/ - 164.90.252.249
appzily.com - https://www.mailcheck.ai/domain/appzily.com - https://temp-mail.io/en/
cashflow35.com - https://www.mailcheck.ai/domain/cashflow35.com - https://temp-mail.io/en/
cloud-mail.top - https://temp-mail.io/en/
mac-24.com - https://temp-mail.io/en/
thejoker5.com - https://temp-mail.io/en/
greencafe24.com - https://temp-mail.io/en/
crepeau12.com - https://temp-mail.io/en/
appzily.com - https://temp-mail.io/en/
coffeetimer24.com - https://temp-mail.io/en/
popcornfarm7.com - …
> feat: domains from 2022-02-14

- disposable_email_blocklist.conf
closes #316 
Adds the latest temp-mail.org domains
siberpay.com - temp-mail.org - 174.138.110.99
tonaeto.com - temp-mail.org - 174.138.110.99
songsign.com - temp-mail.org - 174.138.110.99
superyp.com - temp-mail.org - 174.138.110.99
shopxda.com - temp-mail.org - 174.138.110.99
sofrge.com - temp-mail.org - 174.138.110.99
snece.com - temp-mail.org - 174.138.110.99
tourcc.com - temp-mail.org - 174.138.110.99
uhe2.com - temp-mail.org - 174.138.110.99
trgfu.com - temp-mail.org - 174.138.110.99
volaj.com - temp-mail.org - 174.138.110.99
cutradition.com - mail.tm
freeml.net - dropmail.me
chenbot.email - http://findtempmail.com/
pipemail.space - findtempmail.com
> feat: domains for 2022-03-16

- README.md
First of all this fixes the issue the `open()` call is missing. Otherwise `blocklist` is a string instead of a file, and doesn't have a `readlines()` method.
I also added some small improvements. I know it's just a simple code sample, but most people will probably copy&paste it and use it as a base instead of writing new code from scratch. Hence, I made added some small improvments that improve the code without making it much longer or more complex. These changes are:
- Use an unordered `set` instead of an ordered `list` to reduce the lookup complexity from *O(n)* to *O(1)*.
- Use a `with` statement to close the blocklist file automatically after reading
- Use `str.partition` instead of `str.split` for more consistent results in case `email` is not a valid email address.
See the …
> Improvements for the Python example code

- disposable_email_blocklist.conf
Hey, just catched a few domains, which were not part of the list at https://10minutemail.net/ while testing my implementation of the list.
See attached files:
Cheers,
Max
> Add cdfaq com and nezid.com domains

- allowlist.conf
Per the discussion/decision from This domain (discussed in https://github.com/disposable-email-domains/disposable-email-domains/pull/298), moving this domain to the allowlist.
See more about the service at [relay.firefox.com](https://relay.firefox.com)
> Add mozmail.com to allowlist.conf (Firefox Relay)

- disposable_email_blocklist.conf
New domain used by https://www.mohmal.com/ar/inbox
> add boxmail.lol domain (used by mohmal.com)

- disposable_email_blocklist.conf
[tempmail.lol](https://tempmail.lol/) -> `beaconmessenger.com` ; `cringemonster.com` ; `inactivemachine.com` ; `lamasticots.com` ; `theeyeoftruth.com`
> Add tempmail.lol email domains

- disposable_email_blocklist.conf
Addresses `@fextemp.com` can be registered at https://tempmail.plus
> Add fextemp.com to blocklist

- disposable_email_blocklist.conf
Added tmmbt.net as domain. I just had a registration from this domain and checked it as a disposable 10 minute email provider.
If you are adding domains please state where one can generate a disposable email address which uses the added domains, so the maintainers can verify it. Without this information your PR will be closed.
> Added additional disposable domain

- disposable_email_blocklist.conf
The disposable e-mail domains from InstAddr ( https://m.kuku.lu/ )
"instmail.uk" domain is used for the disposable e-mail address with expiration.
"eripo.net", "nyasan.com", and "shchiba.uk" domains are available only in Japan.
> Add some domains from InstAddr

- disposable_email_blocklist.conf
Adds the following email domains which can all be registered at https://fakermail.com/
`@chewydonut.com`
`@hypenated-domain.com`
`@itsjiff.com`
`@lilspam.com`
`@mailbiscuit.com`
`@pizzajunk.com`
`@realquickemail.com`
`@sharkfaces.com`
`@silenceofthespam.com`
`@snakebutt.com`
`@sociallymediocre.com`
`@spamfellas.com`
`@spamsandwich.com`
`@thespamfather.com`
`@whaaaaaaaaaat.com`
The generator on that page picks a random domain each time, but the full list is retrieved from https://fakermail.com/api/domains on pageload
> Add fakermail.com domains

- allowlist.conf
Added other domains all connected to sneakemail.com which is already on the allow list.
See:
https://github.com/FGRibreau/mailchecker/issues/139
https://github.com/FGRibreau/mailchecker/pull/150
https://github.com/FGRibreau/mailchecker/pull/319
https://github.com/nfacha/temporary-email-list/pull/2
https://github.com/FGRibreau/mailchecker/pull/414
Alredy present:
sneakemail.com
snkmail.com
Added:
liamekaens.com
snkml.com
> Added other sneakemail.com domains to allowlist

- disposable_email_blocklist.conf
https://github.com/disposable-email-domains/disposable-email-domains/issues/388
The company I work to, was receiving bot account creation attacks based on these three disposable domains:
@dshfjdafd.cloud -> email-fake.com
@alina-schiesser.ch -> MegoX Temp Mail
@tmail.io -> https://tmail.io/
> issue-388 alina-schiesser.ch dshfdafd.cloud tmail.io

- disposable_email_blocklist.conf
The disposable e-mail domains from InstAddr ( https://m.kuku.lu/ )
> Add 7 new domains from InstAddr

- disposable_email_blocklist.conf
The disposable e-mail domains from [InstAddr](https://m.kuku.lu/)
"onlyapp.net" domain is available only in Japan.
"akugu.com" and "pwpwa.com" domains are originally available for premium users, but it seems available also for free users now.
> Add 4 new domains from InstAddr

- disposable_email_blocklist.conf
You can go to https://temp-mail.org/ to get new temporary emails.
Please go to the website in incognito mode. If you close the incognito mode and open the url in incognito again it has a chance of giving you temporary email from a different domain.
> added emails from https://temp-mail.org

- allowlist.conf
- disposable_email_blocklist.conf
Hello,
I am looking to contribute to your project by updating the list of disposable email domains to help mitigate the use of temporary emails. In this pull request, I have added new disposable email domains to `disposable_email_blocklist.conf` and included a safe domain in `allowlist.conf`.
- **c01.kr**: Can be generated at [temp-mail.winsub.kr](https://temp-mail.winsub.kr), a Korean disposable email provider.
- **copyhome.win, iralborz.bid, kumli.racing, ruu.kr**: Can be generated at [ruu.kr](https://ruu.kr), another Korean disposable email provider.
- **gosarlar.com**: Can be generated at [temp-mail.org](https://temp-mail.org), a widely used disposable email service.
- **kakao.com**: This domain is provided by Kakao, the company behind KakaoTalk, for use by its members in South Korea. …
> add allowlist(kakao.com) and blocklist(from 3 sources)

- disposable_email_blocklist.conf
Years ago pointed to mailinator, now they don't. They are my personal domains and when I put them into use I began using them with regular email provider at Fastmail. Please process the removal, thanks.
> Remove xwaretech domains

- allowlist.conf
We've had various problems over the last year (when we came into ownership of this domain) with service providers and even post-facto account suspensions due to old denylist data from various sources. Some databases recognize the domain as non-disposable, and some do not.
Perhaps express enumeration in the allowlist will help us.
If you are adding domains please state where one can generate a disposable email address which uses the added domains, so the maintainers can verify it. Without this information your PR will be closed.
> Add ubicloud.com to allowlist

- disposable_email_blocklist.conf
Add dpptd.com and rteet.com to the blocklist since they both redirect to https://www.1secmail.com/, which is on the blocklist
> Add additional alt domains for 1secmail.com

- disposable_email_blocklist.conf
Addresses can be generated at the same domain: https://tmail.link
> Add tmail.link

- disposable_email_blocklist.conf
This is an active site providing temporary email addresses
currentmail.com
The generated email addresses are on the `@currentmail.com` domain
> Add an additional temporary mail provider to the blocklist, 

- disposable_email_blocklist.conf
The aver(.)com domain is owned by Aver USA (https://www.averusa.com) which provides "visual collaboration solutions" (i.e. they make video conferencing products). Their support email is support.usa@aver.com.
> Removing aver(.)com as it's a legitimate company

- README.md
This pull request adds a link to the npm package "disposable-email-domains-js" in the README.md file. This will provide users with an alternative way to access the package on GitHub.
I recently created an NPM package. I believe that linking it similarly to other languages and frameworks can help prevent the reinvention of the wheel.
> Add npm package link for README.md

- disposable_email_blocklist.conf
hthlm.com is a https://10minutemail.com/ disposable address.
> Add hthlm.com to blocklist

- disposable_email_blocklist.conf
I generated it at [Temp Mail](https://temp-mail.org/en/)
It can also be verified at https://verifymail.io/domain/bflcafe.com
Below is a screenshot of proof:
> Add bflcafe.com to blocklist

- disposable_email_blocklist.conf
Adds `confmin.com` and `cantozil.com` from https://temp-mail.org/, and `ytnhy.com` from https://10minutemail.com/
> Add confmin.com, cantozil.com and ytnhy.com

- disposable_email_blocklist.conf
Domains from temp-mail.org used for temporary disposable emailes.
> added emails from temp-mail.org

- disposable_email_blocklist.conf
I generated an email address for the `one-ml.com` domain using the website at https://www.onetime-mail.com. All the domains in this list have MX records pointing back at themselves, but they all have the same IPv4 address of `203.152.198.135`.
This list can be verified with the following script:
```bash
#!/usr/bin/env bash
set -euo pipefail
PR="471"
PROVIDER="onetime-mail.com"
A_RECORDS=("203.152.198.135")
while read -r line; do
echo "Checking $line"
mx="$(dig +short MX "$line" | cut -d' ' -f2-)"
a="$(dig +short A "${mx[@]}")"
grep_args=()
for search_record in "${A_RECORDS[@]}"; do
grep_args+=('-e' "^${search_record//./\.}$")
done
grep -q "${grep_args[@]}" <<< "$a" || echo "$line is not part of $PROVIDER (MX: $(paste -s -d' ' - <<< "${mx:-missing}"))"
done < <(curl -fsSL -o- …
```
> Add domains from onetime-mail.com

- disposable_email_blocklist.conf
This PR enhances the repository by adding support for disposable email domains used by [getnada.cc](https://getnada.cc/), a popular temporary email service.
📌 Added Domains
The following domains have been included:
```
getmailfree.cc
getnada.cc
mailnada.cc
mailnada.com
email10p.org
email-free.online
```
> Add support for `getnada.cc` disposable email domains

- disposable_email_blocklist.conf
decep.com
https://www.usercheck.com/domain/decep.com
> adding decep.com

- disposable_email_blocklist.conf
Found a new domain that is used by temp-mail.io
https://www.ipqualityscore.com/domain-reputation/mkzaso.com
> New domain from temp-mail.io

- disposable_email_blocklist.conf
---
Adds `citmo.net`, `dreamclarify.org`, and `thetechnext.net` from tempmailo.com to the list.
They can be generated at https://tempmailo.com. Screenshots:
> add citmo.net, dreamclarify.org, thetechnext.net from tempmailo.com

- disposable_email_blocklist.conf
These are all the domains of noopmail.org, the screenshot shows them all, and you can also visit https://noopmail.org/ to see them.
> Add all "noopmail.org" domains

- disposable_email_blocklist.conf
All domains for "10minutemail.one" are not listed directly on the page but can be viewed by clicking the "Change" button on https://10minutemail.one/. Each domain uses the IP address `51.79.50.159` and is hosted on `OVH SAS (AS16276)`. Below, I’ve included one screenshot for each domain in the list.
- cmdkl.com
- comyze.org
- pngrise.com
- translateid.com
> Add all "10minutemail.one" domains

- disposable_email_blocklist.conf
linshi-email.com and awamail.com don’t show all domains at once. 
you have to click the change button to refresh them. I’ve attached screenshots of all the domains below.
awamail.com:
- say0.com
- yun.pics
- awa.pics
- vips.pics
linshi-email.com:
- iwatermail.com
> Add all "awamail.com" and "linshi-email.com" domains

- disposable_email_blocklist.conf
All domains for "tempmail.now" are not listed directly on the page but can be viewed by clicking the "Change Email" button on https://tempmail.now/. Each domain uses the IP address `167.71.185.60` and is hosted on `DigitalOcean, LLC (AS14061)`. Below, I’ve included one screenshot for each domain in the list.
- fira.my
- fynix.sbs
- httpsgreenwichmeantime.in
- lunor.cfd
- lynex.sbs
- vetra.cyou
- vexi.my
- vulca.sbs
- xenta.cfd
- zira.my
- zivox.sbs
> Add all "tempmail.now" domains

- disposable_email_blocklist.conf
All domains for "mailbox49.com" are not listed directly on the page but can be viewed by clicking the "Change Address" button on https://mailbox49.com/en. Each domain uses the IP address `134.195.211.168` and is hosted on `MULTACOM CORPORATION (AS35916)`. Below, I’ve included one screenshot for each domain in the list.
> Note: The domain amex409.monster and oxmail.homes have no MX record but I added them to the commit because in the site they are shown as domains to generate mails which means that at any time they can add MX records to them.
- dusrui.com
- anquandx.com
- tempmailfree.net
- amex409.monster
- tgduck.com
- mailbox49.com
- chatworkstation.com
- oxmail.homes
- bootssl.com
- kcoporation.com
- afternea.sbs
- codeguard.net
- certificenter.com
- pyskillsgame.com
- …
> Add all "mailbox49.com" domains

- disposable_email_blocklist.conf
Simply open infoexperts.online and you will receive an email address ending in dsitip.com
> domain used by infoexperts.online

- disposable_email_blocklist.conf
All domains for "22.do" appear directly on the page, which can be viewed by clicking on the dropdown that displays the domains at https://22.do/. Each domain is hosted by `Cloudflare, Inc. (AS13335)`. Below, I have included a screenshot for each domain in the list.
> Note: The linshiyou.com and youxiang.dev domains are also from this provider but are already added to the repository.
- All domains
> Add all "22.do" domains

- disposable_email_blocklist.conf
All domains for "priyo.email" appear directly on the page, which can be viewed by clicking the "Change" button on https://priyo.email/en. Each domain uses the IP address `51.91.252.134` and is hosted on `OVH SAS (AS16276)`. Below, I’ve included the screenshots.
- All domains
> Add all "priyo.email" domains

- disposable_email_blocklist.conf
All domains for "tempmail.pw" appear directly on the page, which can be viewed by clicking the "Select Domain" dropdown on https://tempmail.pw/change. Each domain is hosted by `Cloudflare, Inc. (AS13335)`. Below, I’ve included the screenshot.
- All domains
> Add all "tempmail.pw" domains

- disposable_email_blocklist.conf
All domains for "onetimeinbox.com" are not listed directly on the page but can be viewed by clicking the "New" button on https://onetimeinbox.com/. Each domain uses the IP address `109.123.248.176` and is hosted on `Contabo GmbH (AS51167)`. Below, I’ve included one screenshot for each domain in the list.
- dumalu.com
- gonida.co.uk
- gonida.com
- gonida.uk
- rotomails.co.uk
- rotomails.com
> feat(domains): Add onetimeinbox.com domains

- disposable_email_blocklist.conf
All domains for "freetempmail.org" are not listed directly on the page but can be viewed by clicking the "Change Email" button on https://www.freetempmail.org/. Each domain is hosted by `Cloudflare, Inc. (AS13335)`. Below, I have included a screenshot for each domain in the list.
- bored.lol
- fog.one
- gni8.com
- killyourtime.com
- ug.wtf
> feat(domains): Add freetempmail.org domains

- disposable_email_blocklist.conf
This is a domain from adguard's free temp mail service
https://adguard.com/en/adguard-temp-mail/overview.html
> feat(domains): Add adguard.com temp mail domain

- disposable_email_blocklist.conf
The website https://temp-inbox.com/ uses the domain `victoriaalison.com`, which appears to be the only one offered. The domain uses the IP address `134.122.76.215` and is hosted on `DigitalOcean, LLC (AS14061)`. Below, I’ve included the screenshot.
- victoriaalison.com
> feat(domains): Add temp-inbox.com domain

- disposable_email_blocklist.conf
domains are put under MX DNS tmail.delivery (a service where you can pay to receive emails on your own domain)
* mailmay.org
* mailapril.org
domains are all are put under MX DNS hi.mail.cx
* nqmo.com
* end.tw
* 6n9.net
domains are all under the same cloudflare nameservers (same as zemail.me) and MX DNS is on mx.stackmail.com
* zarkbin.store
* itsedit.click
* optivex.cfd
* lynwise.shop
* e-pool.uk
* e-pool.co.uk
domains are all under the same MX DNS: mxb.tempamail.com
* koletter.com
* opemails.com
* uiemail.com
domains are all under the same nameservers (same as tempumail.com)
* edumail.edu.pl
* yomail.edu.pl
* best-hosting.biz
* best-vpn.xyz
* goomail.club
* toolnator.plus
> feat(domains): add domains from multiple providers

- disposable_email_blocklist.conf
When entering https://temp-mail.best/ the only domain that appears is `temp-mail.best` when generating a new address.
- temp-mail.best
> feat(lists): add temp-mail.best domain

- disposable_email_blocklist.conf
All domains can be viewed by going to https://edumail.icu/ and clicking on “Domain Dropdown”.
> This commit includes second-level domains.
> feat(domains): add edumail.icu domains

- disposable_email_blocklist.conf
All domains can be viewed by going to https://tempumail.com/ and clicking on the "Domain Dropdown".
> This commit includes second-level domains.
> feat(domains): add tempumail.com domain

- disposable_email_blocklist.conf
We've seen spam/abuse behavior and mass automated account creation attempts from these email domains at Stytch. 
You can purchase disposable emails from these domains via https://quix.email ([FAQ](https://quix.email/faq)). I've filtered out those from commonly-used free domains like Gmail and Hotmail.
> Add sites associated with quix.email

- disposable_email_blocklist.conf
Not a disposable email domain
```
;; QUESTION SECTION:
;xrho.com.                      IN      MX
;; ANSWER SECTION:
xrho.com.               300     IN      MX      39 route1.mx.cloudflare.net.
xrho.com.               300     IN      MX      72 route3.mx.cloudflare.net.
xrho.com.               300     IN      MX      54 route2.mx.cloudflare.net.
```
> Remove xrho.com

- disposable_email_blocklist.conf
This PR adds the jobzyy.com domain, generated from [Temp-Mail](https://temp-mail.org/en/), to the disposable email domains list. This domain was not previously included.
> Add jobzyy.com to disposable email domains

- disposable_email_blocklist.conf
newaddr.com - abuse link on homepage goes to https://magical.kuku.lu/page.contact.php?type=MailNow which is the support form for InstAddr, a disposable email provider.
http://133.130.102.20/ (MX record IP) redirects to https://m.kuku.lu/en.php also.
> Add newaddr.com

- disposable_email_blocklist.conf
Latest domains list from https://priyo.email - this is the set of domains available when you select the "Change" button and look at the domains options.
> Add latest priyo.email domains
