disposable-email-domains/disposable-email-domains

disposable_email_blacklist.conf
Added 20mail.it from http://www.20minutemail.com/
=> Added 20mail.it

disposable_email_blacklist.conf
Used by http://www.throwawaymail.com/
=> Add throam.com

disposable_email_blacklist.conf
I have one problem user that just keeps revealing more services ;)
=> New batch from http://temp-mail.org/

disposable_email_blacklist.conf
Used by http://www.tempail.com/temp-email
=> Added dodsi.com - temporary mail domain from http://tempail.com

disposable_email_blacklist.conf
Also dropped a few domains that were filtered out by the whitelist file.
=> Added new throwawaymail.com domain

disposable_email_blacklist.conf
=> Added clipmail.eu domain on blacklist

disposable_email_blacklist.conf
=> Added top1post.ru domain on blacklist

disposable_email_blacklist.conf
See http://www.mail-temporaire.fr/
=> Added email-jetable.fr & more domains on blacklist

disposable_email_blacklist.conf
=> Added more domains from mytemp.email

disposable_email_blacklist.conf
See https://www.emailondeck.com
=> Added domain from emailondeck.com

disposable_email_blacklist.conf
=> Added swift10minutemail.com

disposable_email_blacklist.conf
=> Added more domains from email-fake.com

disposable_email_blacklist.conf
=> Add throwam.com

disposable_email_blacklist.conf
Added a new domain from 10minutemail.net to the list
=> New alias tqoai.com from 10minutemail.net

disposable_email_blacklist.conf
I have added new stexsy.com from https://temp-mail.org
=> new alias stexsy.com from temp-mail.org

disposable_email_blacklist.conf
new domain xzsok.com from 10minutemail.net
=> new domain xzsok.com from 10minutemail.net

disposable_email_blacklist.conf
fix from pr https://github.com/martenson/disposable-email-domains/pull/60
=> Add fake domain names

disposable_email_blacklist.conf
=> reject dsiay.com

disposable_email_blacklist.conf
=> added housat.com

disposable_email_blacklist.conf
Found this list very useful thus far, so here are my contributions
=> Added 18 new domains from  temp-mail.org and data from my website

disposable_email_blacklist.conf
=> Pokemail net

disposable_email_blacklist.conf
You have to register: https://api.freemail.hu/site/register
=> freemail.hu is not disposable

disposable_email_blacklist.conf
=> nincsmail.hu provides *@nincsmail.com addresses

disposable_email_blacklist.conf
You have to register: https://www.c2.hu/new_user_registration.html
=> c2.hu is not disposable

disposable_email_blacklist.conf
we've recently started seeing traffic from hidebox.org and thought it could be included here! /cc @martenson
=> add hidebox.org

disposable_email_blacklist.conf
=> adding getnada.com

disposable_email_blacklist.conf
One of the 10minutemail.com domains
=> Add mvrht.net

disposable_email_blacklist.conf
https://temp-mail.ru/en/option/change
=> Add new domains

disposable_email_blacklist.conf
See https://github.com/martenson/disposable-email-domains/blob/master/disposable_email_blacklist.conf#L1976
=> Remove subdomains for uu.gl which is already black listed

disposable_email_blacklist.conf
New domains:
- [30mail.ir](http://30mail.ir/)
=> Add new domains to black list

disposable_email_blacklist.conf
Service URL: https://mailto.space/
=> Add domains from mailto.space to the blacklist

disposable_email_blacklist.conf
Here's the today domains screenshot for `temp-mail.org`
=> [temp-mail.org] New domains

disposable_email_blacklist.conf
Here's the screenshot from tempmailaddress.com
=> [tempmailaddress.com] Added new domain

disposable_email_blacklist.conf
Here are the screenshots.
Only notice is about the domain `reddit.usa.cc` as `usa.cc` is a Free Domain Registration Service, `usa.cc` can't be blacklisted. So I explicitly added `reddit.usa.cc` instead of `usa.cc`
=> [mytemp.email] Added new domains

disposable_email_blacklist.conf
=> Add mailbox92.biz to the blacklist

disposable_email_blacklist.conf
=> [emailtemporal.org] Added new domains

disposable_email_blacklist.conf, whitelist.conf
I got two notices about this PR.
- `dwse.edu.pl` as `.edu.pl` is a top level domain so we can't black list `.edu.pl`
- `freemail.tweakly.net` as `tweakly.net` provide a web interface with sign up required for accessing mail with `tweakly.net` domain, but they also provide `freemail.tweakly.net`, `msrc.ml` and `twkly.ml` on `mytemp.email` platform.
See this screenshot about `tweakly.net`:
Here are the screenshots from mytemp.email:
=> [mytemp.email] Added a bunch of new domains

disposable_email_blacklist.conf, whitelist.conf
=> Move snkmail.com from blacklist to whitelist

disposable_email_blacklist.conf
Added new domains managed by mohmal.com. Thanks,
=> New Domains From Mohmal

.travis.yml, disposable_email_blacklist.conf, requirements.txt, verify.py
=> tinkering with travis

disposable_email_blacklist.conf
These are domain from  https://github.com/ivolo/disposable-email-domains/blob/master/index.json.
=> Include a bunch of new email domains

README.md
- Optimised and cleaned, faster by about 32.5% on my machine
- Added optional parameter to select the blacklist file, defaults to "disposable_email_blacklist.conf" file in the same directory as script
- Renamed and indented according to PSR-2
- Added notes about email validation and mbstring
=> Updated PHP code snippet

disposable_email_blacklist.conf
[Zulip recently switched to using this library](https://github.com/zulip/zulip/commit/41f8618c04e9720f816ab0a5c8c50320928230ac), this adds a number of domains that were in their original list but are not in this list.
I've only added the domains with valid MX records, see below:
* `anotherdomaincyka.tk`
* `anotherdomaincyka.tk. 17 IN MX 10 mail.b-io.co.`
* `antichef.com`
* `antichef.com. 1626 IN MX 10 gourmet7.spamgourmet.com.`
* `antichef.net`
* `antichef.net. 1517 IN MX 10 gourmet7.spamgourmet.com.`
* `arur01.tk`
* `arur01.tk. 126 IN MX 10 mail.b-io.co.`
* `azazazatashkent.tk`
* `azazazatashkent.tk. 265 IN MX 10 mail.b-io.co.`
* `bione.co`
* `bione.co. 1026 IN MX 20 smx2.web-hosting.com.`
* `bione.co. 1026 IN MX 30 smx3.web-hosting.com.`
* `bione.co. 1026 IN MX 10 smx1.web-hosting.com.` …
=> Add more domains

disposable_email_blacklist.conf
https://www.stopforumspam.com/domain/molms.com
https://github.com/ivolo/disposable-email-domains
=> add molms.com

README.md
Updated in `disposable-email-domains==0.0.35`.
=> Update Python package usage

disposable_email_blocklist.conf
=> Fixes #180 add domains from temp-mail.org

disposable_email_blocklist.conf
@martenson Please, make a review
=> Add ezehe.com

disposable_email_blocklist.conf
@martenson please, make review
=> Update disposable_email_blacklist.conf as disscused in #149

disposable_email_blocklist.conf
Please check https://www.gaggle.net/product/safetytipline/
=> gaggle.net is not an disposable domain

disposable_email_blocklist.conf
Hello.
I propose to add:
```
alpha-web.net
desoz.com
anonmail.top
jaqis.com
```
=> alpha-web.net, desoz.com, anonmail.top, jaqis.com

disposable_email_blocklist.conf
Added new domains from emailtemporal.org and ordered them
=> Added new domains from emailtemporal.org

disposable_email_blocklist.conf
I added the himail.online domain since it is a new temporary mail provider.
=> Added himail.online domain

disposable_email_blocklist.conf
Domains from:
https://tempomail.org
https://tempmailo.com
https://temp-mail.org
https://www.tempmailaddress.com
https://www.ahem.email
https://www.trash-mail.com
=> Add domains

disposable_email_blocklist.conf
offered to me on https://www.throwawaymail.com/en
=> added mywrld.top and mywrld.site

disposable_email_blocklist.conf
Fixes #220. 
Two domains on this list we explicitly allow: spamgourmet.com and sneakemail.com
=> Add domains from The Directory of the Web

disposable_email_blocklist.conf
From here
https://www.mohmal.com/pt/inbox
=> Add emailcu.icu

disposable_email_blocklist.conf, verify.py
=> More CI checks

disposable_email_blocklist.conf
Related to https://github.com/martenson/disposable-email-domains/pull/240 but without allowlist changes.
=> Add domains from temporary-mail.net

disposable_email_blocklist.conf
=> Blacklist fosil.pro

disposable_email_blocklist.conf
lerbhe.com is disposable according to https://fakecheck.email/lerbhe.com
=> Add lerbhe.com

disposable_email_blocklist.conf
See https://fakecheck.email/tmpemails.com
=> Add tmpemails.com

disposable_email_blocklist.conf
See https://fakecheck.email/emailgenerator.de
=> Add emailgenerator.de

disposable_email_blocklist.conf
Add domains used in creating temporary email service( https://m.kuku.lu/en.php ).
=> Add domains used in https://m.kuku.lu/

disposable_email_blocklist.conf
The list that I want to merge can be found on https://tempmail.plus 
Spammers actively use this service to register free accounts on our sites
=> Additional temporary domains

disposable_email_blocklist.conf
Add all related 1secmail domains:
- 1secmail.com
- esiix.com
- wwjmp.com
- 1secmail.net
- 1secmail.org
See https://fakecheck.email/1secmail.com
=> Add 1secmail.com and all related domains

disposable_email_blocklist.conf
Hey :wave:,
this email service was causing me a lot of trouble with tons of throw away emails. I thought it would be useful to add it.
You can visit their website [here](http://supersave.net).
By the way, thanks for this great list!
=> Add supersave.net

disposable_email_blocklist.conf
Adds bptfp.net an alias of https://10minutemail.com/
=> Adds bptfp.net

disposable_email_blocklist.conf
These all came from refreshing https://10minutemail.com/
=> Add more 10minutemail domains

disposable_email_blocklist.conf
=> Add ayakamail.cf into list

disposable_email_blocklist.conf
Add nthrl.com and nvhrw.com (10minutemail.com)
https://10minutemail.com/
nthrl.com|nthrl.com
---|---
```
❯ dig mx nthrl.com
; <<>> DiG 9.10.6 <<>> mx nthrl.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37046
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;nthrl.com.			IN	MX
;; ANSWER SECTION:
nthrl.com.		86400	IN	MX	50 prd-smtp.10minutemail.com.
;; Query time: 470 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Wed Jan 19 09:40:10 JST 2022
;; MSG SIZE  rcvd: 76
```
```
❯ dig mx nvhrw.com
; <<>> DiG 9.10.6 <<>> mx nvhrw.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12032
;; flags: qr rd …
```
=> add domains of 10minutemail com

disposable_email_blocklist.conf
dropped entries with no MX and no found way to use
closes #274
=> cleanup and followup for #274

disposable_email_blocklist.conf
adding new domains from https://10minutemail.net/history.html
=> feat: adding new 10minutemail domains

disposable_email_blocklist.conf
13 new ones for you.
Found these on tempmail.io:
airmailbox.website - https://tempmail.io/settings/
givememail.club - https://tempmail.io/settings/
mailfirst.icu - https://tempmail.io/settings/
mepost.pw - https://tempmail.io/settings/
onemail.host - https://tempmail.io/settings/
These were on m.kuku.lu:
sendnow.win - https://m.kuku.lu/
instaddr.ch - https://m.kuku.lu/
kpay.be - https://m.kuku.lu/
Submic was on temp-mail.org, and the other two had the same IP:
submic.com - https://temp-mail.org/en/ - 174.138.127.74
spruzme.com - https://temp-mail.org/en/ - same IP Address - 174.138.127.74
sueshaw.com - https://temp-mail.org/en/ - same IP Address - 174.138.127.74
These both had the same erin.biz mx records, which are part of the https://m.kuku.lu/ group above
kbox.li - erinn.biz
tensi.org …
=> feat: domains for 2022-03-01

README.md
I contributed the PHP code in readme. Now I'm a go dev.
=> ADD GO CODE!!!!!!!! 🥰😍🔥✨

disposable_email_blocklist.conf
The domains can be found here https://tempmail.plus/en/#!
=> add https://tempmail.plus domains

disposable_email_blocklist.conf
China-focused disposable email service: https://www.linshi-email.com/en
=> Add domain from https://www.linshi-email.com/en

disposable_email_blocklist.conf
- Add new domain from 1secmail
=> Add new domain from 1secmail

disposable_email_blocklist.conf
Add new domain from https://temp-mail.org/fr/ > @cupbest.com
=> Add new domain from temp-mail.org

README.md
It appears a few people are using this package already, so here it is in the README should others see it here first and think it may be of use. It's updated daily in GitHub actions and tagged as a patch release for Composer updates on Packagist. Suggestions welcome!
=> Adds PHP Composer package details to README

disposable_email_blocklist.conf
I've added 16 new domains from https://emailfake.com (that domain itself plus 15 domains you can choose from at the top of that page).
=> feat: add domains from https://emailfake.com

disposable_email_blocklist.conf
Email addresses can be generated at https://ahmedkhlef.com/
=> Add ahmedkhlef.com

disposable_email_blocklist.conf
=> add more moakt domains

disposable_email_blocklist.conf
Add fallinhay.com from https://www.fakemail.net/
example screenshot:
=> Add fallinhay.com from https://www.fakemail.net/

allowlist.conf, disposable_email_blocklist.conf
randomly came across this
xref https://github.com/ivolo/disposable-email-domains/pull/938
=> remove personal domain

README.md, disposable_email_blocklist.conf
Added Bash script example, + @spymail.com domain. email can be generated at spymail.com
=> Added Bash script example, + spymail.com domain

disposable_email_blocklist.conf
Emails addresses can be generated at https://temp-mail.org/  and at https://www.disposablemail.com/
=> Add emails to list

disposable_email_blocklist.conf
[https://akmail.in/](https://akmail.in/)
=> Added akmail.in

disposable_email_blocklist.conf
[temp-mail.org](https://temp-mail.org/) -> `in2reach.com` ; `larland.com` ; `meidecn.com` ; `pixiil.com` ; `saeoil.com` ; `soombo.com` ; `syinxun.com`
[10minutemail.com](https://10minutemail.com/) -> `bbitf.com` ; `bbitj.com` ; `bbitq.com` ; `tcwlm.com` ; `tcwlx.com` ; `tpwlb.com`
[fakemail.net](https://www.fakemail.net/) -> `fullangle.org`
[emailondeck.com](https://www.emailondeck.com/) -> `ereplyzy.com`
=> Update temp-mail.org email domains

disposable_email_blocklist.conf
[developermail.com](https://developermail.com/) -> `developermail.com`
=> Add developermail.com

disposable_email_blocklist.conf
If you are adding domains please state where one can generate a disposable email address which uses the added domains, so the maintainers can verify it. Without this information your PR will be closed.
=> Add gufum.com

disposable_email_blocklist.conf
`bugfoo.com` -> [mail.tm](https://mail.tm/) 
`extracurricularsociety.com` -> [mail.gw](https://mail.gw/)
=> Add mail.tm and mail.gw email domains

disposable_email_blocklist.conf
[emailnator.com](https://www.emailnator.com/) -> `femailtor.com` ; `mydefipet.live` ; `psnator.com` ; `smartnator.com`
=> Add Gmailnator email domains

disposable_email_blocklist.conf
[tmpx.email](https://tmpx.email) -> `tmpx.sa.com`
[mail.gw/en](https://mail.gw/en) -> `futuramind.com`
[yopmail.com/en/alternate-domains](https://yopmail.com/en/alternate-domains) -> `doojazz.com` , `fr.cr` (as of #362)
`civikli.com` (as of #363)
closes #362
closes #363
=> Add 5 new domains

disposable_email_blocklist.conf
closes #371
closes #312 (domain already in the list)
closes #342
=> add domains from tempmailo.com

disposable_email_blocklist.conf
=> add bukhariansiddur.com and triots.com

README.md
=> update examples in readme

disposable_email_blocklist.conf
Two new domains listed at 1secmail.com:
=> add two new domains from 1secmail.com

disposable_email_blocklist.conf
=> Add three domains from receivemail(dot)org

disposable_email_blocklist.conf
- http://exelica.com
- kinda.email / kindamail.com
- mymaily.lol (https://www.mohmal.com) - see also https://verifymail.io/domain/mymaily.lol
=> Add 4 new domains (kinda, kmail, exelica)

disposable_email_blocklist.conf
=> add emailbin.net

disposable_email_blocklist.conf
Addition of mailers.edu.pl , outlook.edu.pl and privmail.edu.pl from https://etempmail.com/zh
=> Addition of mailers.edu.pl , outlook.edu.pl and privmail.edu.pl from https://etempmail.com/zh

disposable_email_blocklist.conf
> If you are adding domains please state where one can generate a disposable email address which uses the added domains, so the maintainers can verify it. Without this information your PR will be closed.
You can create those domains at https://muellmail.com.
=> Add domains from muellmail.com.

disposable_email_blocklist.conf
Hello, Dear Admin.
I hope this message reaches you. My name is kuchibashi.
I am the operator of a social networking platform in Japan and we use a list you maintain to block users who try to register with disposable email addresses on our platform. During our periodic checks, some email addresses were not included in the existing list, allowing users with disposable email addresses to slip through.
I have identified and included two additional disposable email addresses in this pull request.
tatsu.uk: https://m.kuku.lu/
maskmy.id: https://skiff.com/quick-alias
Thank you for maintaining this valuable resource.
Best regards,
mendakon
=> add tatsu.uk, maskmy.id

README.md
Examples in so much languages, my favorite one is missing.
=> Add Java example

disposable_email_blocklist.conf
You can go to these 4 domains to be able to set up temporary emails:
- linshiyou.com
- qabq.com
- snapmail.cc
- youxiang.dev
=> Adding temporary email domains

disposable_email_blocklist.conf
**10mail.xyz**: 
- Generatable via: https://dropmail.me/en/ (just keep on refreshing)
- https://www.stopforumspam.com/domain/10mail.xyz
**laste.ml**: 
- Generatable via: https://dropmail.me/en/ (just keep on refreshing)
- https://www.stopforumspam.com/domain/laste.ml
=> Added additional dropmail.me domains

disposable_email_blocklist.conf
You can go to `https://temp-mail.org/` to get new temporary emails.
Please go to the website in incognito mode. If you close the incognito mode and open the url in incognito again it has a chance of giving you temporary email from a different domain.
=> more temp-mail.org domains

disposable_email_blocklist.conf
Added domains from 1secmail.org
=> Added email addresses from 1secmail.org

disposable_email_blocklist.conf
Domains from https://tempr.email/
=> Add active domains from tempr.email

disposable_email_blocklist.conf
Found them on https://temp-mail.org
=> Added more temp-mail.org domains

disposable_email_blocklist.conf
=> add mails from inboxes com

README.md
Added Swift / SwiftUI Example (for iOS) in Readme.
Thank you :)
=> Add Swift Code Example

disposable_email_blocklist.conf
Can generate here: https://mail.tm/en/
=> Add navalcadets.com

allowlist.conf, disposable_email_blocklist.conf
=> Remove vfemail.net from blocklist

disposable_email_blocklist.conf
domain is no longer used for this. thanks!
=> remove letmeinonthis.com

.github/workflows/pr.yml
=> rename master to main in ghwf

disposable_email_blocklist.conf
=> added tacomail.de

disposable_email_blocklist.conf
=> Disposable domains 6 january 2025

disposable_email_blocklist.conf
Spotted on https://temp-mail.org/en
=> Add anypng.com

disposable_email_blocklist.conf
Found two domains and for reference here are the screenshots- 
1. fundapk.com
2. fanicle.com
Thank You!
=> added two domains fanicle.com and fundapk.com

disposable_email_blocklist.conf
asciibinder.net is an temporary email and can be obtained  from https://tempmailo.com
cyclelove.cc is an temporary email and can be obtained  from https://tempmailo.com
deallabs.org is an temporary email and can be obtained  from https://disposablemail.com
dotvu.net is an temporary email and can be obtained  from https://tempmail.so
dotzi.net is an temporary email and can be obtained  from https://tempmail.so
driftz.net is an temporary email and can be obtained  from https://tempmail.so
drivz.net is an temporary email and can be obtained  from https://tempmail.so
flyzy.net is an temporary email and can be obtained  from https://tempmail.so
mailbai.com is an temporary email and can be obtained  from https://tempmail.so
mixzu.net is an temporary email and can be obtained  from …
=> Add to disposable_email_blocklist.conf

disposable_email_blocklist.conf
=> add domains from `yopmail com`

disposable_email_blocklist.conf
servicetr.me : https://www.servicee.es/mailbox
servicee.es : https://www.servicee.es/mailbox
universall.me : https://www.servicee.es/mailbox
ymeet.pro : https://verifymail.io/domain/ymeet.pro
kytstore.com : https://verifymail.io/domain/kytstore.com
jarars.com : https://verifymail.io/domain/jarars.com
=> add new domains: `servicetr.me`, `servicee.es`, `universall.me`.

disposable_email_blocklist.conf
xref https://github.com/disposable-email-domains/disposable-email-domains/pull/519#issuecomment-2449000116
=> add domains from `tempmail io`

disposable_email_blocklist.conf
=> egvoo.com is a new one that temp-mail.org is using

disposable_email_blocklist.conf
=> adding corhash net

disposable_email_blocklist.conf
https://www.usercheck.com/domain/boyaga.com
=> Add boyaga.com

disposable_email_blocklist.conf
=> Add nokdot.com

disposable_email_blocklist.conf
=> Add deenur.com

disposable_email_blocklist.conf
=> Add oronny.com

disposable_email_blocklist.conf
=> Add dizigg.com

disposable_email_blocklist.conf
=> Add exclussi.com

disposable_email_blocklist.conf
=> add `1sec-mail com`

disposable_email_blocklist.conf
from https://10minemail.com/ 
lushosa.com
cotigz.com
asaption.com
agiuse.com
and from https://www.tempmail.lol/en/
jailbreakeverything.com
expiredtoaster.org
underseagolf.com
awesome47.com
undeadbank.com
pigeonprotocol.com
=> added email generated from 2 sites 

disposable_email_blocklist.conf
- tempmail.id.vn
- 1trick.net
- nghienplus.io.vn
- tempmail.ckvn.edu.vn
=> Add tempmail.id.vn domains

disposable_email_blocklist.conf
Corroborated via https://www.ipqualityscore.com/domain-reputation/haren.uk and https://verifymail.io/domain/haren.uk
Also, https://m.kuku.lu/en.php#p708 generates addresses with the same MX server:
```
$ dig sendnow.win mx
; <<>> DiG 9.18.30-0ubuntu0.24.04.2-Ubuntu <<>> sendnow.win mx
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40530
;; flags: qr rd ra; QUERY: 1, ANSWER: 10, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;sendnow.win.			IN	MX
;; ANSWER SECTION:
sendnow.win.		300	IN	MX	10 recv6.erinn.biz.
sendnow.win.		300	IN	MX	10 recv7.erinn.biz.
sendnow.win.		300	IN	MX	10 recv8.erinn.biz.
sendnow.win.		300	IN	MX	10 recv1.erinn.biz.
sendnow.win.		300	IN	MX	10 recv100.erinn.biz. …
```
=> Add haren.uk

disposable_email_blocklist.conf
=> add new `kuku lu` dmns

disposable_email_blocklist.conf
This is the only domain of `tempemailgen.com` by going to their website you can generate disposable mails with it at https://tempemailgen.com/en
=> Add multiple disposable providers

disposable_email_blocklist.conf
=> add acedby.com to blocklist

disposable_email_blocklist.conf
Tempmail service https://tempmail.world generates the following domains:
```
business-degree.live
cancer-treatment.xyz
credit-loans.xyz
examstudy.xyz
```
=> Add tempmail.world domains

disposable_email_blocklist.conf
=> add hidmail.org

disposable_email_blocklist.conf
=> Add mail10m.com

disposable_email_blocklist.conf
"eztempmail.com" shows all domains at https://www.eztempmail.com/change.
- All domains
=> feat(domains): Add eztempmail.com domains

disposable_email_blocklist.conf
You can view the domains by going to https://www.1secmail.cc/en/change and clicking on the dropdown with the domains.
- All domains
=> feat(domains): add 1secmail.cc domains

disposable_email_blocklist.conf
=> feat(domain): add temp-mail.org domain

disposable_email_blocklist.conf
=> Add emailondeck.com domain

disposable_email_blocklist.conf
=> Add mails.org domain

disposable_email_blocklist.conf
=> Add dustbin.one domain

disposable_email_blocklist.conf
https://adguard.com/en/adguard-temp-mail/overview.html
=> Add adguard.com domain

disposable_email_blocklist.conf
=> Add 10minutemail.net domains

disposable_email_blocklist.conf
=> Add mohmal.com domain

disposable_email_blocklist.conf
=> Add with.lt domains

disposable_email_blocklist.conf
=> Add jjk.app domain

disposable_email_blocklist.conf
=> Add email10min.com domain

disposable_email_blocklist.conf
=> Add tempp-mails.com domains

disposable_email_blocklist.conf
To see the domains of https://best-temp-mail.com/ you need to refresh the page each time to get a new address.
- aakk.link:
=> feat(domains): add best-temp-mail.com domain

disposable_email_blocklist.conf
=> Add temp-mail.cc domain

disposable_email_blocklist.conf
=> Add zudy.info domains

disposable_email_blocklist.conf
=> Add tempmail.vip domains

disposable_email_blocklist.conf
=> Add temp-mail.now domains

disposable_email_blocklist.conf
=> Add trashmail.com domains

disposable_email_blocklist.conf
=> Add nicemail.cc domains

disposable_email_blocklist.conf
To see all the domains of this provider, you need to go to https://boomlify.com/en/dashboard/ and click the "Domain Dropdown" to view all domains.
- All domains
=> feat(domains): add boomlify.com domains

disposable_email_blocklist.conf
To see this domain, you have to go to https://temp-mail.org/en/ and use your browser's incognito mode or a VPN. This provider changes its domains every day.
- kimdyn.com:
> Closes #671
=> feat(domains): add temp-mail.org domain

disposable_email_blocklist.conf
To see the domain you need to enter https://incognitomail.co/ and click the "Create new email" button or by just refreshing the site.
- mailpro.live:
=> feat(domains): add incognitomail.co domain

disposable_email_blocklist.conf
All domains can be viewed by going to https://temp-mail.io/en and clicking on the "Change" button.
- mrotzis.com
- wnbaldwy.com
- xkxkud.com
=> feat(domains): add temp-mail.io domains

disposable_email_blocklist.conf
The domain can be viewed by going to https://temp-mail.org/en/ and clicking on the "Change" button or refreshing the website.
=> feat(domains): add temp-mail.org domains

disposable_email_blocklist.conf
All domains can be viewed by going to https://tempmailg.com/en and clicking on the "Change" button.
- All domains
=> feat(domains): add tempmailg.com domains

disposable_email_blocklist.conf
=> - Added forexru.com and modirosa.com

disposable_email_blocklist.conf
This site doesn't display all domains directly. You need to enter https://smailpro.com/, click the green plus icon, and then click 'create'.
addmails.com:
begemail.com:
drewzen.com:
dugmail.com:
eartin.net:
ewebrus.com:
famamail.com:
ikomail.com:
kabamail.com:
mailpull.com:
mailshou.com:
odeask.com:
ofanda.com:
phyones.com:
pusmail.com:
solerbe.net:
sonjj.edu.pl:
storegmail.net:
tumroc.net:
upsnab.net:
woopros.com:
=> feat(domains): add smailpro.com domains

disposable_email_blocklist.conf
=> feat: add reusable.email to blocklist

disposable_email_blocklist.conf
=> Add temp-mail.org domains

disposable_email_blocklist.conf
Evidence: https://viewdns.info/reversemx/?mx=prd-smtp.10minutemail.com;
Closes unmaintained PR #470
=> Add 10minutemail.com domains

disposable_email_blocklist.conf
=> Add bitmens.com
